// <auto-generated-from>material-color-utilities/java</auto-generated-from>
// Translated to C# for M3E4Unity. Names follow the Java original on purpose.
using System;
using System.Collections.Generic;
using System.Linq;

namespace M3E4Unity.MaterialColor
{
using DeltaConstraint = M3E4Unity.MaterialColor.ToneDeltaPair.DeltaConstraint;
using Platform = M3E4Unity.MaterialColor.DynamicScheme.Platform;
using SpecVersion = M3E4Unity.MaterialColor.ColorSpec.SpecVersion;

/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */




sealed class ColorSpec2026 : ColorSpec2025 {

  private static double findBestToneForChroma(
      double hue, double chroma, double tone, bool byDecreasingTone) {
    double answer = tone;
    Hct bestCandidate = Hct.from(hue, chroma, answer);
    while (bestCandidate.getChroma() < chroma) {
      if (tone < 0 || tone > 100) {
        break;
      }
      tone += byDecreasingTone ? -1.0 : 1.0;
      Hct newCandidate = Hct.from(hue, chroma, tone);
      if (bestCandidate.getChroma() < newCandidate.getChroma()) {
        bestCandidate = newCandidate;
        answer = tone;
      }
    }
    return answer;
  }

  private static double tMaxC(TonalPalette palette) {
    return tMaxC(palette, 0, 100);
  }

  private static double tMaxC(TonalPalette palette, double lowerBound, double upperBound) {
    return tMaxC(palette, lowerBound, upperBound, 1);
  }

  private static double tMaxC(
      TonalPalette palette, double lowerBound, double upperBound, double chromaMultiplier) {
    double answer =
        findBestToneForChroma(palette.getHue(), palette.getChroma() * chromaMultiplier, 100, true);
    return MathUtils.clampDouble(lowerBound, upperBound, answer);
  }

  private static double tMinC(TonalPalette palette) {
    return tMinC(palette, 0, 100);
  }

  private static double tMinC(TonalPalette palette, double lowerBound, double upperBound) {
    double answer = findBestToneForChroma(palette.getHue(), palette.getChroma(), 0, false);
    return MathUtils.clampDouble(lowerBound, upperBound, answer);
  }

  private static ContrastCurve getContrastCurve(double defaultContrast) {
    if (defaultContrast == 1.5) {
      return new ContrastCurve(1.5, 1.5, 3, 5.5);
    } else if (defaultContrast == 3) {
      return new ContrastCurve(3, 3, 4.5, 7);
    } else if (defaultContrast == 4.5) {
      return new ContrastCurve(4.5, 4.5, 7, 11);
    } else if (defaultContrast == 6) {
      return new ContrastCurve(6, 6, 7, 11);
    } else if (defaultContrast == 7) {
      return new ContrastCurve(7, 7, 11, 21);
    } else if (defaultContrast == 9) {
      return new ContrastCurve(9, 9, 11, 21);
    } else if (defaultContrast == 11) {
      return new ContrastCurve(11, 11, 21, 21);
    } else if (defaultContrast == 21) {
      return new ContrastCurve(21, 21, 21, 21);
    } else {
      // Shouldn't happen.
      return new ContrastCurve(defaultContrast, defaultContrast, 7, 21);
    }
  }

  public override DynamicColor surface() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("surface")
            .setPalette(s => s.neutralPalette)
            .setTone(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 4.0 : 98.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.surface().toBuilder().extendSpecVersion(SpecVersion.SPEC_2026, color2026).build();
  }

  public override DynamicColor surfaceDim() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("surface_dim")
            .setPalette(s => s.neutralPalette)
            .setTone(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 4.0 : 87.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 1.0 : 1.7;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.surfaceDim().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor surfaceBright() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("surface_bright")
            .setPalette(s => s.neutralPalette)
            .setTone(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 18.0 : 98.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 1.7 : 1.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.surfaceBright().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor surfaceContainerLowest() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("surface_container_lowest")
            .setPalette(s => s.neutralPalette)
            .setTone(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 0.0 : 100.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.surfaceContainerLowest().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor surfaceContainerLow() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("surface_container_low")
            .setPalette(s => s.neutralPalette)
            .setTone(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 6.0 : 96.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.25;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.surfaceContainerLow().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor surfaceContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("surface_container")
            .setPalette(s => s.neutralPalette)
            .setTone(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 9.0 : 94.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.4;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.surfaceContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor surfaceContainerHigh() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("surface_container_high")
            .setPalette(s => s.neutralPalette)
            .setTone(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 12.0 : 92.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.5;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.surfaceContainerHigh().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor surfaceContainerHighest() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("surface_container_highest")
            .setPalette(s => s.neutralPalette)
            .setTone(
                s => {
                  if (s.variant == Variant.CMF) {
                    return s.isDark ? 15.0 : 90.0;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.7;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.surfaceContainerHighest().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onSurface() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_surface")
            .setPalette(s => s.neutralPalette)
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.7;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.isDark ? getContrastCurve(11) : getContrastCurve(9))
            .build();
    return base.onSurface().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onSurfaceVariant() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_surface_variant")
            .setPalette(s => s.neutralPalette)
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.7;
                  } else { // Undefined variant
                    return 0.0;
                  }
                })
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.isDark ? getContrastCurve(6) : getContrastCurve(4.5))
            .build();
    return base.onSurfaceVariant().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor outline() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("outline")
            .setPalette(s => s.neutralPalette)
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.7;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => getContrastCurve(3))
            .build();
    return base.outline().toBuilder().extendSpecVersion(SpecVersion.SPEC_2026, color2026).build();
  }

  public override DynamicColor outlineVariant() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("outline_variant")
            .setPalette(s => s.neutralPalette)
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.7;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => getContrastCurve(1.5))
            .build();
    return base.outlineVariant().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor inverseSurface() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("inverse_surface")
            .setPalette(s => s.neutralPalette)
            .setTone(s => s.isDark ? 98.0 : 4.0)
            .setChromaMultiplier(
                s => {
                  if (s.variant == Variant.CMF) {
                    return 1.7;
                  } else { // Undefined use case
                    return 0.0;
                  }
                })
            .setIsBackground(true)
            .build();
    return base.inverseSurface().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor inverseOnSurface() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("inverse_on_surface")
            .setPalette(s => s.neutralPalette)
            .setBackground(s => inverseSurface())
            .setContrastCurve(s => getContrastCurve(7))
            .build();
    return base.inverseOnSurface().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor primary() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("primary")
            .setPalette(s => s.primaryPalette)
            .setTone(
                s =>
                    s.sourceColorHct.getChroma() <= 12
                        ? (s.isDark ? 80.0 : 40.0)
                        : s.sourceColorHct.getTone())
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => getContrastCurve(4.5))
            .setToneDeltaPair(
                s =>
                    s.platform == DynamicScheme.Platform.PHONE
                        ? new ToneDeltaPair(
                            primaryContainer(), primary(), 5, TonePolarity.RELATIVE_LIGHTER, ToneDeltaPair.DeltaConstraint.FARTHER)
                        : null)
            .build();
    return base.primary().toBuilder().extendSpecVersion(SpecVersion.SPEC_2026, color2026).build();
  }

  public override DynamicColor primaryDim() {
    // Remapped to primary in 2026 spec.
    DynamicColor color2026 = primary().toBuilder().setName("primary_dim").build();
    return base.primaryDim().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onPrimary() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_primary")
            .setPalette(s => s.primaryPalette)
            .setBackground(s => primary())
            .setContrastCurve(s => getContrastCurve(6))
            .build();
    return base.onPrimary().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor primaryContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("primary_container")
            .setPalette(s => s.primaryPalette)
            .setTone(
                s => {
                  if (!s.isDark && s.sourceColorHct.getChroma() <= 12) {
                    return 90.0;
                  }
                  return s.sourceColorHct.getTone() > 55
                      ? MathUtils.clampDouble(61, 90, s.sourceColorHct.getTone())
                      : MathUtils.clampDouble(30, 49, s.sourceColorHct.getTone());
                })
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.primaryContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onPrimaryContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_primary_container")
            .setPalette(s => s.primaryPalette)
            .setBackground(s => primaryContainer())
            .setContrastCurve(s => getContrastCurve(6))
            .build();
    return base.onPrimaryContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor primaryFixed() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("primary_fixed")
            .setPalette(s => s.primaryPalette)
            .setTone(
                s => {
                  DynamicScheme tempS =
                      DynamicScheme.from(s, /* isDark= */ false, /* contrastLevel= */ 0.0);
                  return primaryContainer().getTone(tempS);
                })
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.primaryFixed().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor primaryFixedDim() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("primary_fixed_dim")
            .setPalette(s => s.primaryPalette)
            .setTone(s => primaryFixed().getTone(s))
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setToneDeltaPair(
                s => new ToneDeltaPair(primaryFixedDim(), primaryFixed(), 5, TonePolarity.DARKER, ToneDeltaPair.DeltaConstraint.EXACT))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.primaryFixedDim().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onPrimaryFixed() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_primary_fixed")
            .setPalette(s => s.primaryPalette)
            .setBackground(s => primaryFixed().getTone(s) > 57 ? primaryFixedDim() : primaryFixed())
            .setContrastCurve(s => getContrastCurve(7))
            .build();
    return base.onPrimaryFixed().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onPrimaryFixedVariant() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_primary_fixed_variant")
            .setPalette(s => s.primaryPalette)
            .setBackground(s => primaryFixed().getTone(s) > 57 ? primaryFixedDim() : primaryFixed())
            .setContrastCurve(s => getContrastCurve(4.5))
            .build();
    return base.onPrimaryFixedVariant().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor secondary() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("secondary")
            .setPalette(s => s.secondaryPalette)
            .setTone(s => s.isDark ? tMinC(s.secondaryPalette) : tMaxC(s.secondaryPalette))
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => getContrastCurve(4.5))
            .setToneDeltaPair(
                s =>
                    s.platform == DynamicScheme.Platform.PHONE
                        ? new ToneDeltaPair(
                            secondaryContainer(), secondary(), 5, TonePolarity.RELATIVE_LIGHTER, ToneDeltaPair.DeltaConstraint.FARTHER)
                        : null)
            .build();
    return base.secondary().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor secondaryDim() {
    // Remapped to secondary in 2025 spec.
    DynamicColor color2026 = secondary().toBuilder().setName("secondary_dim").build();
    return base.secondaryDim().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onSecondary() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_secondary")
            .setPalette(s => s.secondaryPalette)
            .setBackground(s => secondary())
            .setContrastCurve(s => getContrastCurve(6))
            .build();
    return base.onSecondary().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor secondaryContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("secondary_container")
            .setPalette(s => s.secondaryPalette)
            .setTone(
                s =>
                    s.isDark
                        ? tMinC(s.secondaryPalette, 20, 49)
                        : tMaxC(s.secondaryPalette, 61, 90))
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.secondaryContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onSecondaryContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_secondary_container")
            .setPalette(s => s.secondaryPalette)
            .setBackground(s => secondaryContainer())
            .setContrastCurve(s => getContrastCurve(6))
            .build();
    return base.onSecondaryContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor secondaryFixed() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("secondary_fixed")
            .setPalette(s => s.secondaryPalette)
            .setTone(
                s => {
                  DynamicScheme tempS =
                      DynamicScheme.from(s, /* isDark= */ false, /* contrastLevel= */ 0.0);
                  return secondaryContainer().getTone(tempS);
                })
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.secondaryFixed().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor secondaryFixedDim() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("secondary_fixed_dim")
            .setPalette(s => s.secondaryPalette)
            .setTone(s => secondaryFixed().getTone(s))
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setToneDeltaPair(
                s => new ToneDeltaPair(secondaryFixedDim(), secondaryFixed(), 5, TonePolarity.DARKER, ToneDeltaPair.DeltaConstraint.EXACT))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.secondaryFixedDim().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onSecondaryFixed() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_secondary_fixed")
            .setPalette(s => s.secondaryPalette)
            .setBackground(
                s => secondaryFixed().getTone(s) > 57 ? secondaryFixedDim() : secondaryFixed())
            .setContrastCurve(s => getContrastCurve(7))
            .build();
    return base.onSecondaryFixed().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onSecondaryFixedVariant() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_secondary_fixed_variant")
            .setPalette(s => s.secondaryPalette)
            .setBackground(
                s => secondaryFixed().getTone(s) > 57 ? secondaryFixedDim() : secondaryFixed())
            .setContrastCurve(s => getContrastCurve(4.5))
            .build();
    return base.onSecondaryFixedVariant().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor tertiary() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("tertiary")
            .setPalette(s => s.tertiaryPalette)
            .setTone(
                s =>
                    s.sourceColorHctList.Count > 1
                        ? s.sourceColorHctList.get(1).getTone()
                        : s.sourceColorHct.getTone())
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => getContrastCurve(4.5))
            .setToneDeltaPair(
                s =>
                    s.platform == DynamicScheme.Platform.PHONE
                        ? new ToneDeltaPair(
                            tertiaryContainer(), tertiary(), 5, TonePolarity.RELATIVE_LIGHTER, ToneDeltaPair.DeltaConstraint.FARTHER)
                        : null)
            .build();
    return base.tertiary().toBuilder().extendSpecVersion(SpecVersion.SPEC_2026, color2026).build();
  }

  public override DynamicColor tertiaryDim() {
    // Remapped to tertiary in 2025 spec.
    DynamicColor color2026 = tertiary().toBuilder().setName("tertiary_dim").build();
    return base.tertiaryDim().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onTertiary() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_tertiary")
            .setPalette(s => s.tertiaryPalette)
            .setBackground(s => tertiary())
            .setContrastCurve(s => getContrastCurve(6))
            .build();
    return base.onTertiary().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor tertiaryContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("tertiary_container")
            .setPalette(s => s.tertiaryPalette)
            .setTone(
                s => {
                  Hct secondarySourceColorHct =
                      s.sourceColorHctList.Count > 1
                          ? s.sourceColorHctList.get(1)
                          : s.sourceColorHct;
                  return secondarySourceColorHct.getTone() > 55
                      ? MathUtils.clampDouble(61, 90, secondarySourceColorHct.getTone())
                      : MathUtils.clampDouble(20, 49, secondarySourceColorHct.getTone());
                })
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.tertiaryContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onTertiaryContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_tertiary_container")
            .setPalette(s => s.tertiaryPalette)
            .setBackground(s => tertiaryContainer())
            .setContrastCurve(s => getContrastCurve(6))
            .build();
    return base.onTertiaryContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor tertiaryFixed() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("tertiary_fixed")
            .setPalette(s => s.tertiaryPalette)
            .setTone(
                s => {
                  DynamicScheme tempS =
                      DynamicScheme.from(s, /* isDark= */ false, /* contrastLevel= */ 0.0);
                  return tertiaryContainer().getTone(tempS);
                })
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.tertiaryFixed().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor tertiaryFixedDim() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("tertiary_fixed_dim")
            .setPalette(s => s.tertiaryPalette)
            .setTone(s => tertiaryFixed().getTone(s))
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setToneDeltaPair(
                s => new ToneDeltaPair(tertiaryFixedDim(), tertiaryFixed(), 5, TonePolarity.DARKER, ToneDeltaPair.DeltaConstraint.EXACT))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.tertiaryFixedDim().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onTertiaryFixed() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_tertiary_fixed")
            .setPalette(s => s.tertiaryPalette)
            .setBackground(
                s => tertiaryFixed().getTone(s) > 57 ? tertiaryFixedDim() : tertiaryFixed())
            .setContrastCurve(s => getContrastCurve(7))
            .build();
    return base.onTertiaryFixed().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onTertiaryFixedVariant() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_tertiary_fixed_variant")
            .setPalette(s => s.tertiaryPalette)
            .setBackground(
                s => tertiaryFixed().getTone(s) > 57 ? tertiaryFixedDim() : tertiaryFixed())
            .setContrastCurve(s => getContrastCurve(4.5))
            .build();
    return base.onTertiaryFixedVariant().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor error() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("error")
            .setPalette(s => s.errorPalette)
            .setTone(s => tMaxC(s.errorPalette))
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => getContrastCurve(4.5))
            .setToneDeltaPair(
                s =>
                    s.platform == DynamicScheme.Platform.PHONE
                        ? new ToneDeltaPair(errorContainer(), error(), 5, TonePolarity.RELATIVE_LIGHTER, ToneDeltaPair.DeltaConstraint.FARTHER)
                        : null)
            .build();
    return base.error().toBuilder().extendSpecVersion(SpecVersion.SPEC_2026, color2026).build();
  }

  public override DynamicColor errorDim() {
    // Remapped to error in 2026 spec.
    DynamicColor color2026 = error().toBuilder().setName("error_dim").build();
    return base.errorDim().toBuilder().extendSpecVersion(SpecVersion.SPEC_2026, color2026).build();
  }

  public override DynamicColor onError() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_error")
            .setPalette(s => s.errorPalette)
            .setBackground(s => error())
            .setContrastCurve(s => getContrastCurve(6))
            .build();
    return base.onError().toBuilder().extendSpecVersion(SpecVersion.SPEC_2026, color2026).build();
  }

  public override DynamicColor errorContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("error_container")
            .setPalette(s => s.errorPalette)
            .setTone(s => s.isDark ? tMinC(s.errorPalette) : tMaxC(s.errorPalette))
            .setIsBackground(true)
            .setBackground(s => highestSurface(s))
            .setContrastCurve(s => s.contrastLevel > 0 ? getContrastCurve(1.5) : null)
            .build();
    return base.errorContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }

  public override DynamicColor onErrorContainer() {
    DynamicColor color2026 =
        new DynamicColor.Builder()
            .setName("on_error_container")
            .setPalette(s => s.errorPalette)
            .setBackground(s => errorContainer())
            .setContrastCurve(s => getContrastCurve(6))
            .build();
    return base.onErrorContainer().toBuilder()
        .extendSpecVersion(SpecVersion.SPEC_2026, color2026)
        .build();
  }
}
}
