// <auto-generated-from>material-color-utilities/java</auto-generated-from>
// Translated to C# for M3E4Unity. Names follow the Java original on purpose.
using System;
using System.Collections.Generic;
using System.Linq;

namespace M3E4Unity.MaterialColor
{
using DeltaConstraint = M3E4Unity.MaterialColor.ToneDeltaPair.DeltaConstraint;
using Platform = M3E4Unity.MaterialColor.DynamicScheme.Platform;
using SpecVersion = M3E4Unity.MaterialColor.ColorSpec.SpecVersion;

/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



/** A utility class to get the correct color spec for a given spec version. */
public sealed class ColorSpecs {

  private static readonly ColorSpec SPEC_2021 = new ColorSpec2021();
  private static readonly ColorSpec SPEC_2025 = new ColorSpec2025();
  private static readonly ColorSpec SPEC_2026 = new ColorSpec2026();

  public static ColorSpec get() {
    return get(SpecVersion.SPEC_2021);
  }

  public static ColorSpec get(SpecVersion specVersion) {
    return get(specVersion, false);
  }

  public static ColorSpec get(SpecVersion specVersion, bool isExtendedFidelity) {
    switch (specVersion) {
case ColorSpec.SpecVersion.SPEC_2025: return SPEC_2025;
case ColorSpec.SpecVersion.SPEC_2026: return SPEC_2026;
default: return SPEC_2021;
}
  }

  private ColorSpecs() {}
}
}
