// <auto-generated-from>material-color-utilities/java</auto-generated-from>
// Translated to C# for M3E4Unity. Names follow the Java original on purpose.
using System;
using System.Collections.Generic;
using System.Linq;

namespace M3E4Unity.MaterialColor
{
using DeltaConstraint = M3E4Unity.MaterialColor.ToneDeltaPair.DeltaConstraint;
using Platform = M3E4Unity.MaterialColor.DynamicScheme.Platform;
using SpecVersion = M3E4Unity.MaterialColor.ColorSpec.SpecVersion;

/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



/**
 * A color that adjusts itself based on UI state, represented by DynamicScheme.
 *
 * <p>This color automatically adjusts to accommodate a desired contrast level, or other adjustments
 * such as differing in light mode versus dark mode, or what the theme is, or what the color that
 * produced the theme is, etc.
 *
 * <p>Colors without backgrounds do not change tone when contrast changes. Colors with backgrounds
 * become closer to their background as contrast lowers, and further when contrast increases.
 *
 * <p>Prefer the static constructors. They provide a much more simple interface, such as requiring
 * just a hexcode, or just a hexcode and a background.
 *
 * <p>Ultimately, each component necessary for calculating a color, adjusting it for a desired
 * contrast level, and ensuring it has a certain lightness/tone difference from another color, is
 * provided by a function that takes a DynamicScheme and returns a value. This ensures ultimate
 * flexibility, any desired behavior of a color for any design system, but it usually unnecessary.
 * See the default constructor for more information.
 */
public sealed class DynamicColor {
  public readonly string name;
  public readonly Func<DynamicScheme, TonalPalette> palette;
  public readonly Func<DynamicScheme, double> tone;
  public readonly bool isBackground;
  public readonly Func<DynamicScheme, double> chromaMultiplier;
  public readonly Func<DynamicScheme, DynamicColor> background;
  public readonly Func<DynamicScheme, DynamicColor> secondBackground;
  public readonly Func<DynamicScheme, ContrastCurve> contrastCurve;
  public readonly Func<DynamicScheme, ToneDeltaPair> toneDeltaPair;

  public readonly Func<DynamicScheme, double?> opacity;

  private readonly Dictionary<DynamicScheme, Hct> hctCache = new();

  /**
   * A constructor for DynamicColor.
   *
   * <p>_Strongly_ prefer using one of the convenience constructors. This class is arguably too
   * flexible to ensure it can support any scenario. Functional arguments allow overriding without
   * risks that come with subclasses.
   *
   * <p>For example, the default behavior of adjust tone at max contrast to be at a 7.0 ratio with
   * its background is principled and matches accessibility guidance. That does not mean it's the
   * desired approach for _every_ design system, and every color pairing, always, in every case.
   *
   * <p>For opaque colors (colors with alpha = 100%).
   *
   * @param name The name of the dynamic color.
   * @param palette Function that provides a TonalPalette given DynamicScheme. A TonalPalette is
   *     defined by a hue and chroma, so this replaces the need to specify hue/chroma. By providing
   *     a tonal palette, when contrast adjustments are made, intended chroma can be preserved.
   * @param tone Function that provides a tone, given a DynamicScheme.
   * @param isBackground Whether this dynamic color is a background, with some other color as the
   *     foreground.
   * @param background The background of the dynamic color (as a function of a `DynamicScheme`), if
   *     it exists.
   * @param secondBackground A second background of the dynamic color (as a function of a
   *     `DynamicScheme`), if it exists.
   * @param contrastCurve A `ContrastCurve` object specifying how its contrast against its
   *     background should behave in various contrast levels options.
   * @param toneDeltaPair A `ToneDeltaPair` object specifying a tone delta constraint between two
   *     colors. One of them must be the color being constructed.
   */
  public DynamicColor(
      string name,
      Func<DynamicScheme, TonalPalette> palette,
      Func<DynamicScheme, double> tone,
      bool isBackground,
      Func<DynamicScheme, DynamicColor> background,
      Func<DynamicScheme, DynamicColor> secondBackground,
      ContrastCurve contrastCurve,
      Func<DynamicScheme, ToneDeltaPair> toneDeltaPair) : this(
        name,
        palette,
        tone,
        isBackground,
        background,
        secondBackground,
        contrastCurve,
        toneDeltaPair,
        /* opacity= */ null) {
  }

  /**
   * A constructor for DynamicColor.
   *
   * <p>_Strongly_ prefer using one of the convenience constructors. This class is arguably too
   * flexible to ensure it can support any scenario. Functional arguments allow overriding without
   * risks that come with subclasses.
   *
   * <p>For example, the default behavior of adjust tone at max contrast to be at a 7.0 ratio with
   * its background is principled and matches accessibility guidance. That does not mean it's the
   * desired approach for _every_ design system, and every color pairing, always, in every case.
   *
   * <p>For opaque colors (colors with alpha = 100%).
   *
   * @param name The name of the dynamic color.
   * @param palette Function that provides a TonalPalette given DynamicScheme. A TonalPalette is
   *     defined by a hue and chroma, so this replaces the need to specify hue/chroma. By providing
   *     a tonal palette, when contrast adjustments are made, intended chroma can be preserved.
   * @param tone Function that provides a tone, given a DynamicScheme.
   * @param isBackground Whether this dynamic color is a background, with some other color as the
   *     foreground.
   * @param background The background of the dynamic color (as a function of a `DynamicScheme`), if
   *     it exists.
   * @param secondBackground A second background of the dynamic color (as a function of a
   *     `DynamicScheme`), if it exists.
   * @param contrastCurve A `ContrastCurve` object specifying how its contrast against its
   *     background should behave in various contrast levels options.
   * @param toneDeltaPair A `ToneDeltaPair` object specifying a tone delta constraint between two
   *     colors. One of them must be the color being constructed.
   * @param opacity A function returning the opacity of a color, as a number between 0 and 1.0
   */
  public DynamicColor(
      string name,
      Func<DynamicScheme, TonalPalette> palette,
      Func<DynamicScheme, double> tone,
      bool isBackground,
      Func<DynamicScheme, DynamicColor> background,
      Func<DynamicScheme, DynamicColor> secondBackground,
      ContrastCurve contrastCurve,
      Func<DynamicScheme, ToneDeltaPair> toneDeltaPair,
      Func<DynamicScheme, double?> opacity) : this(
        name,
        palette,
        tone,
        isBackground,
        null,
        background,
        secondBackground,
        (s) => contrastCurve,
        toneDeltaPair,
        opacity) {
  }

  public DynamicColor(
      string name,
      Func<DynamicScheme, TonalPalette> palette,
      Func<DynamicScheme, double> tone,
      bool isBackground,
      Func<DynamicScheme, double> chromaMultiplier,
      Func<DynamicScheme, DynamicColor> background,
      Func<DynamicScheme, DynamicColor> secondBackground,
      Func<DynamicScheme, ContrastCurve> contrastCurve,
      Func<DynamicScheme, ToneDeltaPair> toneDeltaPair,
      Func<DynamicScheme, double?> opacity) {
    this.name = name;
    this.palette = palette;
    this.tone = tone;
    this.isBackground = isBackground;
    this.chromaMultiplier = chromaMultiplier;
    this.background = background;
    this.secondBackground = secondBackground;
    this.contrastCurve = contrastCurve;
    this.toneDeltaPair = toneDeltaPair;
    this.opacity = opacity;
  }

  /**
   * A convenience constructor for DynamicColor.
   *
   * <p>_Strongly_ prefer using one of the convenience constructors. This class is arguably too
   * flexible to ensure it can support any scenario. Functional arguments allow overriding without
   * risks that come with subclasses.
   *
   * <p>For example, the default behavior of adjust tone at max contrast to be at a 7.0 ratio with
   * its background is principled and matches accessibility guidance. That does not mean it's the
   * desired approach for _every_ design system, and every color pairing, always, in every case.
   *
   * <p>For opaque colors (colors with alpha = 100%).
   *
   * <p>For colors that are not backgrounds, and do not have backgrounds.
   *
   * @param name The name of the dynamic color.
   * @param palette Function that provides a TonalPalette given DynamicScheme. A TonalPalette is
   *     defined by a hue and chroma, so this replaces the need to specify hue/chroma. By providing
   *     a tonal palette, when contrast adjustments are made, intended chroma can be preserved.
   * @param tone Function that provides a tone, given a DynamicScheme.
   */
  public static DynamicColor fromPalette(
      string name,
      Func<DynamicScheme, TonalPalette> palette,
      Func<DynamicScheme, double> tone) {
    return new DynamicColor(
        name,
        palette,
        tone,
        /* isBackground= */ false,
        /* background= */ null,
        /* secondBackground= */ null,
        /* contrastCurve= */ null,
        /* toneDeltaPair= */ null);
  }

  /**
   * A convenience constructor for DynamicColor.
   *
   * <p>_Strongly_ prefer using one of the convenience constructors. This class is arguably too
   * flexible to ensure it can support any scenario. Functional arguments allow overriding without
   * risks that come with subclasses.
   *
   * <p>For example, the default behavior of adjust tone at max contrast to be at a 7.0 ratio with
   * its background is principled and matches accessibility guidance. That does not mean it's the
   * desired approach for _every_ design system, and every color pairing, always, in every case.
   *
   * <p>For opaque colors (colors with alpha = 100%).
   *
   * <p>For colors that do not have backgrounds.
   *
   * @param name The name of the dynamic color.
   * @param palette Function that provides a TonalPalette given DynamicScheme. A TonalPalette is
   *     defined by a hue and chroma, so this replaces the need to specify hue/chroma. By providing
   *     a tonal palette, when contrast adjustments are made, intended chroma can be preserved.
   * @param tone Function that provides a tone, given a DynamicScheme.
   * @param isBackground Whether this dynamic color is a background, with some other color as the
   *     foreground.
   */
  public static DynamicColor fromPalette(
      string name,
      Func<DynamicScheme, TonalPalette> palette,
      Func<DynamicScheme, double> tone,
      bool isBackground) {
    return new DynamicColor(
        name,
        palette,
        tone,
        isBackground,
        /* background= */ null,
        /* secondBackground= */ null,
        /* contrastCurve= */ null,
        /* toneDeltaPair= */ null);
  }

  /**
   * Create a DynamicColor from a hex code.
   *
   * <p>Result has no background; thus no support for increasing/decreasing contrast for a11y.
   *
   * @param name The name of the dynamic color.
   * @param argb The source color from which to extract the hue and chroma.
   */
  public static DynamicColor fromArgb(string name, int argb) {
    Hct hct = Hct.fromInt(argb);
    TonalPalette palette = TonalPalette.fromInt(argb);
    return DynamicColor.fromPalette(name, (s) => palette, (s) => hct.getTone());
  }

  /**
   * Returns an ARGB integer (i.e. a hex code).
   *
   * @param scheme Defines the conditions of the user interface, for example, whether or not it is
   *     dark mode or light mode, and what the desired contrast level is.
   */
  public int getArgb(DynamicScheme scheme) {
    int argb = getHct(scheme).toInt();
    if (opacity == null || opacity(scheme) == null) {
      return argb;
    }
    double percentage = opacity(scheme).Value;
    int alpha = MathUtils.clampInt(0, 255, (int) JMath.round(percentage * 255));
    return (argb & 0x00ffffff) | (alpha << 24);
  }

  /**
   * Returns an HCT @object.
   *
   * @param scheme Defines the conditions of the user interface, for example, whether or not it is
   *     dark mode or light mode, and what the desired contrast level is.
   */
  public Hct getHct(DynamicScheme scheme) {
    Hct cachedAnswer = hctCache.get(scheme);
    if (cachedAnswer != null) {
      return cachedAnswer;
    }

    Hct answer = ColorSpecs.get(scheme.specVersion).getHct(scheme, this);
    // NOMUTANTS--trivial test with onerous dependency injection requirement.
    if (hctCache.Count > 4) {
      hctCache.clear();
    }
    // NOMUTANTS--trivial test with onerous dependency injection requirement.
    hctCache[scheme] = answer;
    return answer;
  }

  /** Returns the tone in HCT, ranging from 0 to 100, of the resolved color given scheme. */
  public double getTone(DynamicScheme scheme) {
    return ColorSpecs.get(scheme.specVersion).getTone(scheme, this);
  }

  /**
   * Given a background tone, find a foreground tone, while ensuring they reach a contrast ratio
   * that is as close to ratio as possible.
   */
  public static double foregroundTone(double bgTone, double ratio) {
    double lighterTone = Contrast.lighterUnsafe(bgTone, ratio);
    double darkerTone = Contrast.darkerUnsafe(bgTone, ratio);
    double lighterRatio = Contrast.ratioOfTones(lighterTone, bgTone);
    double darkerRatio = Contrast.ratioOfTones(darkerTone, bgTone);
    bool preferLighter = tonePrefersLightForeground(bgTone);

    if (preferLighter) {
      // "Neglible difference" handles an edge case where the initial contrast ratio is high
      // (ex. 13.0), and the ratio passed to the function is that high ratio, and both the lighter
      // and darker ratio fails to pass that ratio.
      //
      // This was observed with Tonal Spot's On Primary Container turning black momentarily between
      // high and max contrast in light mode. PC's standard tone was T90, OPC's was T10, it was
      // light mode, and the contrast level was 0.6568521221032331.
      bool negligibleDifference =
          JMath.abs(lighterRatio - darkerRatio) < 0.1 && lighterRatio < ratio && darkerRatio < ratio;
      if (lighterRatio >= ratio || lighterRatio >= darkerRatio || negligibleDifference) {
        return lighterTone;
      } else {
        return darkerTone;
      }
    } else {
      return darkerRatio >= ratio || darkerRatio >= lighterRatio ? darkerTone : lighterTone;
    }
  }

  /**
   * Adjust a tone down such that white has 4.5 contrast, if the tone is reasonably close to
   * supporting it.
   */
  public static double enableLightForeground(double tone) {
    if (tonePrefersLightForeground(tone) && !toneAllowsLightForeground(tone)) {
      return 49.0;
    }
    return tone;
  }

  /**
   * People prefer white foregrounds on ~T60-70.0 Observed over time, and also by Andrew Somers
   * during research for APCA.
   *
   * <p>T60 used as to create the smallest discontinuity possible when skipping down to T49 in order
   * to ensure light foregrounds.
   *
   * <p>Since `tertiaryContainer` in dark monochrome scheme requires a tone of 60, it should not be
   * adjusted. Therefore, 60 is excluded here.
   */
  public static bool tonePrefersLightForeground(double tone) {
    return JMath.round(tone) < 60;
  }

  /** Tones less than ~T50 always permit white at 4.5 contrast. */
  public static bool toneAllowsLightForeground(double tone) {
    return JMath.round(tone) <= 49;
  }

  public static Func<DynamicScheme, double> getInitialToneFromBackground(
      Func<DynamicScheme, DynamicColor> background) {
    if (background == null) {
      return (s) => 50.0;
    }
    return (s) => background(s) != null ? background(s).getTone(s) : 50.0;
  }

  public Builder toBuilder() {
    return new Builder()
        .setName(this.name)
        .setPalette(this.palette)
        .setTone(this.tone)
        .setIsBackground(this.isBackground)
        .setChromaMultiplier(this.chromaMultiplier)
        .setBackground(this.background)
        .setSecondBackground(this.secondBackground)
        .setContrastCurve(this.contrastCurve)
        .setToneDeltaPair(this.toneDeltaPair)
        .setOpacity(this.opacity);
  }

  /** Builder for {@link DynamicColor}. */
  public class Builder {
    private string name;
    private Func<DynamicScheme, TonalPalette> palette;
    private Func<DynamicScheme, double> tone;
    private bool isBackground;
    private Func<DynamicScheme, double> chromaMultiplier;
    private Func<DynamicScheme, DynamicColor> background;
    private Func<DynamicScheme, DynamicColor> secondBackground;
    private Func<DynamicScheme, ContrastCurve> contrastCurve;
    private Func<DynamicScheme, ToneDeltaPair> toneDeltaPair;
    private Func<DynamicScheme, double?> opacity;

    public Builder setName(string name) {
      this.name = name;
      return this;
    }

    public Builder setPalette(Func<DynamicScheme, TonalPalette> palette) {
      this.palette = palette;
      return this;
    }

    public Builder setTone(Func<DynamicScheme, double> tone) {
      this.tone = tone;
      return this;
    }

    public Builder setIsBackground(bool isBackground) {
      this.isBackground = isBackground;
      return this;
    }

    public Builder setChromaMultiplier(Func<DynamicScheme, double> chromaMultiplier) {
      this.chromaMultiplier = chromaMultiplier;
      return this;
    }

    public Builder setBackground(Func<DynamicScheme, DynamicColor> background) {
      this.background = background;
      return this;
    }

    public Builder setSecondBackground(
        Func<DynamicScheme, DynamicColor> secondBackground) {
      this.secondBackground = secondBackground;
      return this;
    }

    public Builder setContrastCurve(Func<DynamicScheme, ContrastCurve> contrastCurve) {
      this.contrastCurve = contrastCurve;
      return this;
    }

    public Builder setToneDeltaPair(Func<DynamicScheme, ToneDeltaPair> toneDeltaPair) {
      this.toneDeltaPair = toneDeltaPair;
      return this;
    }

    public Builder setOpacity(Func<DynamicScheme, double?> opacity) {
      this.opacity = opacity;
      return this;
    }

    internal Builder extendSpecVersion(SpecVersion specVersion, DynamicColor extendedColor) {
      validateExtendedColor(specVersion, extendedColor);

      return new Builder()
          .setName(this.name)
          .setIsBackground(this.isBackground)
          .setPalette(
              (s) => {
                Func<DynamicScheme, TonalPalette> palette =
                    s.specVersion.compareTo(specVersion) >= 0
                        ? extendedColor.palette
                        : this.palette;
                return palette != null ? palette(s) : null;
              })
          .setTone(
              (s) => {
                Func<DynamicScheme, double> tone =
                    s.specVersion.compareTo(specVersion) >= 0 ? extendedColor.tone : this.tone;
                return tone(s);
              })
          .setChromaMultiplier(
              (s) => {
                Func<DynamicScheme, double> chromaMultiplier =
                    s.specVersion.compareTo(specVersion) >= 0
                        ? extendedColor.chromaMultiplier
                        : this.chromaMultiplier;
                return chromaMultiplier != null ? chromaMultiplier(s) : 1.0;
              })
          .setBackground(
              (s) => {
                Func<DynamicScheme, DynamicColor> background =
                    s.specVersion.compareTo(specVersion) >= 0
                        ? extendedColor.background
                        : this.background;
                return background != null ? background(s) : null;
              })
          .setSecondBackground(
              (s) => {
                Func<DynamicScheme, DynamicColor> secondBackground =
                    s.specVersion.compareTo(specVersion) >= 0
                        ? extendedColor.secondBackground
                        : this.secondBackground;
                return secondBackground != null ? secondBackground(s) : null;
              })
          .setContrastCurve(
              (s) => {
                Func<DynamicScheme, ContrastCurve> contrastCurve =
                    s.specVersion.compareTo(specVersion) >= 0
                        ? extendedColor.contrastCurve
                        : this.contrastCurve;
                return contrastCurve != null ? contrastCurve(s) : null;
              })
          .setToneDeltaPair(
              (s) => {
                Func<DynamicScheme, ToneDeltaPair> toneDeltaPair =
                    s.specVersion.compareTo(specVersion) >= 0
                        ? extendedColor.toneDeltaPair
                        : this.toneDeltaPair;
                return toneDeltaPair != null ? toneDeltaPair(s) : null;
              })
          .setOpacity(
              (s) => {
                Func<DynamicScheme, double?> opacity =
                    s.specVersion.compareTo(specVersion) >= 0
                        ? extendedColor.opacity
                        : this.opacity;
                return opacity != null ? opacity(s) : null;
              });
    }

    public DynamicColor build() {
      if (this.background == null && this.secondBackground != null) {
        throw new ArgumentException(
            "Color " + name + " has secondBackground defined, but background is not defined.");
      }
      if (this.background == null && this.contrastCurve != null) {
        throw new ArgumentException(
            "Color " + name + " has contrastCurve defined, but background is not defined.");
      }
      if (this.background != null && this.contrastCurve == null) {
        throw new ArgumentException(
            "Color " + name + " has background defined, but contrastCurve is not defined.");
      }
      return new DynamicColor(
          this.name,
          this.palette,
          this.tone == null ? getInitialToneFromBackground(this.background) : this.tone,
          this.isBackground,
          this.chromaMultiplier,
          this.background,
          this.secondBackground,
          this.contrastCurve,
          this.toneDeltaPair,
          this.opacity);
    }

    private void validateExtendedColor(SpecVersion specVersion, DynamicColor extendedColor) {
      if (!this.name.Equals(extendedColor.name)) {
        throw new ArgumentException(
            "Attempting to extend color "
                + this.name
                + " with color "
                + extendedColor.name
                + " of different name for spec version "
                + specVersion
                + ".");
      }
      if (this.isBackground != extendedColor.isBackground) {
        throw new ArgumentException(
            "Attempting to extend color "
                + this.name
                + " as a "
                + (this.isBackground ? "background" : "foreground")
                + " with color "
                + extendedColor.name
                + " as a "
                + (extendedColor.isBackground ? "background" : "foreground")
                + " for spec version "
                + specVersion
                + ".");
      }
    }
  }
}
}
