// <auto-generated-from>material-color-utilities/java</auto-generated-from>
// Translated to C# for M3E4Unity. Names follow the Java original on purpose.
using System;
using System.Collections.Generic;
using System.Linq;

namespace M3E4Unity.MaterialColor
{
using DeltaConstraint = M3E4Unity.MaterialColor.ToneDeltaPair.DeltaConstraint;
using Platform = M3E4Unity.MaterialColor.DynamicScheme.Platform;
using SpecVersion = M3E4Unity.MaterialColor.ColorSpec.SpecVersion;

/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * Describes the relationship in lightness between two colors.
 *
 * <p>'relative_darker' and 'relative_lighter' describes the tone adjustment relative to the surface
 * color trend (white in light mode; black in dark mode). For instance, ToneDeltaPair(A, B, 10,
 * 'relative_lighter', 'farther') states that A should be at least 10 lighter than B in light mode,
 * and at least 10 darker than B in dark mode.
 *
 * <p>See `ToneDeltaPair` for details.
 */
public enum TonePolarity {
  DARKER,
  LIGHTER,
  RELATIVE_DARKER,
  RELATIVE_LIGHTER,
  /**
   * @deprecated Use {@link ToneDeltaPair.DeltaConstraint} instead.
   */
  NEARER,
  /**
   * @deprecated Use {@link ToneDeltaPair.DeltaConstraint} instead.
   */
  FARTHER
}
}
