// <auto-generated-from>material-color-utilities/java</auto-generated-from>
// Translated to C# for M3E4Unity. Names follow the Java original on purpose.
using System;
using System.Collections.Generic;
using System.Linq;

namespace M3E4Unity.MaterialColor
{
using DeltaConstraint = M3E4Unity.MaterialColor.ToneDeltaPair.DeltaConstraint;
using Platform = M3E4Unity.MaterialColor.DynamicScheme.Platform;
using SpecVersion = M3E4Unity.MaterialColor.ColorSpec.SpecVersion;

/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



/** Creates a dictionary with keys of colors, and values of count of the color */
public sealed class QuantizerMap : Quantizer {
  internal Dictionary<int, int> colorToCount;

  public QuantizerResult quantize(int[] pixels, int colorCount) {
    Dictionary<int, int> pixelByCount = new();
    foreach (int pixel in pixels) {
      int newPixelCount = pixelByCount.TryGetValue(pixel, out int currentPixelCount) ? currentPixelCount + 1 : 1;
      pixelByCount[pixel] = newPixelCount;
    }
    colorToCount = pixelByCount;
    return new QuantizerResult(pixelByCount);
  }

  public Dictionary<int, int> getColorToCount() {
    return colorToCount;
  }
}
}
