// <auto-generated-from>material-color-utilities/java</auto-generated-from>
// Translated to C# for M3E4Unity. Names follow the Java original on purpose.
using System;
using System.Collections.Generic;
using System.Linq;

namespace M3E4Unity.MaterialColor
{
using DeltaConstraint = M3E4Unity.MaterialColor.ToneDeltaPair.DeltaConstraint;
using Platform = M3E4Unity.MaterialColor.DynamicScheme.Platform;
using SpecVersion = M3E4Unity.MaterialColor.ColorSpec.SpecVersion;

/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



/**
 * A convenience class for retrieving colors that are constant in hue and chroma, but vary in tone.
 *
 * <p>TonalPalette is intended for use in a single thread due to its stateful caching.
 */
public sealed class TonalPalette {
  internal Dictionary<int, int> cache;
  internal Hct keyColor;
  internal double hue;
  internal double chroma;

  /**
   * Create tones using the HCT hue and chroma from a color.
   *
   * @param argb ARGB representation of a color
   * @return Tones matching that color's hue and chroma.
   */
  public static TonalPalette fromInt(int argb) {
    return fromHct(Hct.fromInt(argb));
  }

  /**
   * Create tones using a HCT color.
   *
   * @param hct HCT representation of a color.
   * @return Tones matching that color's hue and chroma.
   */
  public static TonalPalette fromHct(Hct hct) {
    return new TonalPalette(hct.getHue(), hct.getChroma(), hct);
  }

  /**
   * Create tones from a defined HCT hue and chroma.
   *
   * @param hue HCT hue
   * @param chroma HCT chroma
   * @return Tones matching hue and chroma.
   */
  public static TonalPalette fromHueAndChroma(double hue, double chroma) {
    Hct keyColor = new KeyColor(hue, chroma).create();
    return new TonalPalette(hue, chroma, keyColor);
  }

  private TonalPalette(double hue, double chroma, Hct keyColor) {
    cache = new();
    this.hue = hue;
    this.chroma = chroma;
    this.keyColor = keyColor;
  }

  /**
   * Create an ARGB color with HCT hue and chroma of this Tones instance, and the provided HCT tone.
   *
   * @param tone HCT tone, measured from 0 to 100.0
   * @return ARGB representation of a color with that tone.
   */
  public int tone(int tone) {
    if (!cache.TryGetValue(tone, out int color)) {
      if (tone == 99 && Hct.isYellow(this.hue)) {
        color = averageArgb(this.tone(98), this.tone(100));
      } else {
        color = Hct.from(this.hue, this.chroma, tone).toInt();
      }
      cache[tone] = color;
    }
    return color;
  }

  /** Given a tone, use hue and chroma of palette to create a color, and return it as HCT. */
  public Hct getHct(double tone) {
    if (tone == 99.0 && Hct.isYellow(hue)) {
      return Hct.fromInt(this.tone(99));
    }
    return Hct.from(this.hue, this.chroma, tone);
  }

  /** The chroma of the Tonal Palette, in HCT. Ranges from 0 to ~130 (for sRGB gamut). */
  public double getChroma() {
    return this.chroma;
  }

  /** The hue of the Tonal Palette, in HCT. Ranges from 0 to 360.0 */
  public double getHue() {
    return this.hue;
  }

  /** The key color is the first tone, starting from T50, that matches the palette's chroma. */
  public Hct getKeyColor() {
    return this.keyColor;
  }

  private int averageArgb(int argb1, int argb2) {
    int red1 = ((int)((uint)(argb1) >> 16)) & 0xff;
    int green1 = ((int)((uint)(argb1) >> 8)) & 0xff;
    int blue1 = argb1 & 0xff;
    int red2 = ((int)((uint)(argb2) >> 16)) & 0xff;
    int green2 = ((int)((uint)(argb2) >> 8)) & 0xff;
    int blue2 = argb2 & 0xff;
    int red = JMath.round((red1 + red2) / 2f);
    int green = JMath.round((green1 + green2) / 2f);
    int blue = JMath.round((blue1 + blue2) / 2f);
    return (255 << 24 | (red & 255) << 16 | (green & 255) << 8 | (blue & 255));
  }

  /** Key color is a color that represents the hue and chroma of a tonal palette. */
  internal sealed class KeyColor {
    private readonly double hue;
    private readonly double requestedChroma;

    // Cache that maps tone to max chroma to avoid duplicated HCT calculation.
    private readonly Dictionary<int, double> chromaCache = new();
    private static readonly double MAX_CHROMA_VALUE = 200.0;

    /** Key color is a color that represents the hue and chroma of a tonal palette */
    public KeyColor(double hue, double requestedChroma) {
      this.hue = hue;
      this.requestedChroma = requestedChroma;
    }

    /**
     * Creates a key color from a [hue] and a [chroma]. The key color is the first tone, starting
     * from T50, matching the given hue and chroma.
     *
     * @return Key color [Hct]
     */
    public Hct create() {
      // Pivot around T50 because T50 has the most chroma available, on
      // average. Thus it is most likely to have a direct answer.
      int pivotTone = 50;
      int toneStepSize = 1;
      // Epsilon to accept values slightly higher than the requested chroma.
      double epsilon = 0.01;

      // Binary search to find the tone that can provide a chroma that is closest
      // to the requested chroma.
      int lowerTone = 0;
      int upperTone = 100;
      while (lowerTone < upperTone) {
        int midTone = (lowerTone + upperTone) / 2;
        bool isAscending = maxChroma(midTone) < maxChroma(midTone + toneStepSize);
        bool sufficientChroma = maxChroma(midTone) >= requestedChroma - epsilon;

        if (sufficientChroma) {
          // Either range [lowerTone, midTone] or [midTone, upperTone] has
          // the answer, so search in the range that is closer the pivot tone.
          if (JMath.abs(lowerTone - pivotTone) < JMath.abs(upperTone - pivotTone)) {
            upperTone = midTone;
          } else {
            if (lowerTone == midTone) {
              return Hct.from(this.hue, this.requestedChroma, lowerTone);
            }
            lowerTone = midTone;
          }
        } else {
          // As there is no sufficient chroma in the midTone, follow the direction to the chroma
          // peak.
          if (isAscending) {
            lowerTone = midTone + toneStepSize;
          } else {
            // Keep midTone for potential chroma peak.
            upperTone = midTone;
          }
        }
      }

      return Hct.from(this.hue, this.requestedChroma, lowerTone);
    }

    // Find the maximum chroma for a given tone
    private double maxChroma(int tone) {
      if (!chromaCache.ContainsKey(tone)) {
        double newChroma = Hct.from(hue, MAX_CHROMA_VALUE, tone).getChroma();
        {
          chromaCache[tone] = newChroma;
        }
      }
      return chromaCache.get(tone);
    }
  }
}
}
